# Generated by Django 5.1.2 on 2024-11-02 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('company_size', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.AutoField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_abr', models.CharField(max_length=50)),
                ('skill_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_count', models.IntegerField()),
                ('follower_count', models.IntegerField()),
                ('time_recorded', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanySpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('pay_period', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
                ('formatted_work_type', models.CharField(max_length=50)),
                ('applies', models.IntegerField()),
                ('original_listed_time', models.DateTimeField()),
                ('remote_allowed', models.BooleanField()),
                ('job_posting_url', models.URLField()),
                ('expiry', models.DateTimeField()),
                ('listed_time', models.DateTimeField()),
                ('work_type', models.CharField(max_length=50)),
                ('normalized_salary', models.FloatField()),
                ('zip_code', models.CharField(max_length=10)),
                ('fips', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobIndustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.industry')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_abr', models.CharField(max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.job')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_salary', models.FloatField()),
                ('med_salary', models.FloatField()),
                ('min_salary', models.FloatField()),
                ('pay_period', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('compensation_type', models.CharField(max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapp.job')),
            ],
        ),
    ]
